default: &default
  adapter:  postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost

vagrant: &vagrant
  username: postgres
  password: password
  port: 5432

docker: &docker
  username: postgres
  password:
  host: db

development:
  <<: *default
  <<: *vagrant
  database: just_chew_development

test:
  <<: *default
  <<: *vagrant
  database: just_chew_test

production:
  <<: *default
  <<: *vagrant
  database: just_chew_production
